const products = [
  {
    manhom: 1,
    id: 1,
    name: 'Chuối',
    price: 5000,
    quantity: 10,
    img: 'Cam-Xoan.jpg',
  },
  {
    manhom: 1,
    id: 2,
    name: 'Táo',
    price: 8000,
    quantity: 15,
    img: 'link_to_apple_image.jpg',
  },
  {
    manhom: 1,
    id: 3,
    name: 'Cam',
    price: 7000,
    quantity: 12,
    img: 'link_to_orange_image.jpg',
  },
  {
    manhom: 1,
    id: 4,
    name: 'Lê',
    price: 6000,
    quantity: 20,
    img: 'link_to_pear_image.jpg',
  },
  {
    manhom: 1,
    id: 5,
    name: 'Dứa',
    price: 7500,
    quantity: 8,
    img: 'link_to_pineapple_image.jpg',
  },
  {
    manhom: 1,
    id: 6,
    name: 'Dâu tây',
    price: 10000,
    quantity: 18,
    img: 'link_to_strawberry_image.jpg',
  },
  {
    manhom: 1,
    id: 7,
    name: 'Xoài',
    price: 9000,
    quantity: 14,
    img: 'link_to_mango_image.jpg',
  },
  {
    manhom: 1,
    id: 8,
    name: 'Nho',
    price: 11000,
    quantity: 22,
    img: 'link_to_grape_image.jpg',
  },
  {
    manhom: 1,
    id: 9,
    name: 'Dưa hấu',
    price: 12000,
    quantity: 7,
    img: 'link_to_watermelon_image.jpg',
  },
  {
    manhom: 1,
    id: 10,
    name: 'Mận',
    price: 12000,
    quantity: 7,
    img: 'link_to_watermelon_image.jpg',
  },
  {
    manhom: 1,
    id: 11,
    name: 'Mận',
    price: 6500,
    quantity: 25,
    img: 'link_to_plum_image.jpg',
  },
  {
    manhom: 1,
    id: 12,
    name: 'Lựu',
    price: 8500,
    quantity: 12,
    img: 'link_to_pomegranate_image.jpg',
  },
  {
    manhom: 1,
    id: 13,
    name: 'Cà chua',
    price: 3000,
    quantity: 30,
    img: 'link_to_tomato_image.jpg',
  },
  {
    manhom: 1,
    id: 14,
    name: 'Kiwi',
    price: 9000,
    quantity: 17,
    img: 'link_to_kiwi_image.jpg',
  },
  {
    manhom: 1,
    id: 15,
    name: 'Cà rốt',
    price: 4000,
    quantity: 40,
    img: 'link_to_carrot_image.jpg',
  },
  {
    manhom: 2,
    id: 16,
    name: 'Dứa cải',
    price: 6000,
    quantity: 14,
    img: 'link_to_broccoli_image.jpg',
  },
  {
    manhom: 2,
    id: 17,
    name: 'Mít',
    price: 11000,
    quantity: 8,
    img: 'link_to_jackfruit_image.jpg',
  },
  {
    manhom: 2,
    id: 18,
    name: 'Mang cut',
    price: 7500,
    quantity: 13,
    img: 'link_to_sapodilla_image.jpg',
  },
  {
    manhom: 2,
    id: 19,
    name: 'Chôm chôm',
    price: 13000,
    quantity: 9,
    img: 'link_to_lychee_image.jpg',
  },
  {
    manhom: 2,
    id: 20,
    name: 'Mận xanh',
    price: 9500,
    quantity: 16,
    img: 'link_to_green_plum_image.jpg',
  },
  {
    manhom: 2,
    id: 21,
    name: 'Nho đen',
    price: 12000,
    quantity: 14,
    img: 'link_to_black_grape_image.jpg',
  },
  {
    manhom: 2,
    id: 22,
    name: 'Chuối sứ',
    price: 9000,
    quantity: 20,
    img: 'link_to_cavendish_banana_image.jpg',
  },
  {
    manhom: 2,
    id: 23,
    name: 'Ổi',
    price: 8500,
    quantity: 11,
    img: 'link_to_papaya_image.jpg',
  },
  {
    manhom: 2,
    id: 24,
    name: 'Mứt dứa',
    price: 15000,
    quantity: 20,
    img: 'link_to_dried_pineapple_image.jpg',
  },
  {
    manhom: 2,
    id: 25,
    name: 'Mứt táo',
    price: 12000,
    quantity: 15,
    img: 'link_to_dried_apple_image.jpg',
  },
  {
    manhom: 2,
    id: 26,
    name: 'Mứt lựu',
    price: 18000,
    quantity: 12,
    img: 'link_to_dried_pomegranate_image.jpg',
  },
  {
    manhom: 2,
    id: 27,
    name: 'Mứt chôm chôm',
    price: 16000,
    quantity: 18,
    img: 'link_to_dried_lychee_image.jpg',
  },
  {
    manhom: 2,
    id: 28,
    name: 'Mứt tamarind',
    price: 13000,
    quantity: 25,
    img: 'link_to_dried_tamarind_image.jpg',
  },
  {
    manhom: 2,
    id: 29,
    name: 'Mứt xoài',
    price: 14000,
    quantity: 14,
    img: 'link_to_dried_mango_image.jpg',
  },
  {
    manhom: 2,
    id: 30,
    name: 'Mứt Gừng',
    price: 14000,
    quantity: 14,
    img: 'link_to_dried_mango_image.jpg',
  },
];

const productsJSON = JSON.stringify(products);
localStorage.setItem('products', productsJSON);
